//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace tcpform
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<TblCargas>();
            }
        }
    }
    public partial class TblCargas
    {
        [PrimaryKey]
        public Int64 Id { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String Nome { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String User { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String Ip { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String Funcao { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String Dados { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String Data { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String Estado { get; set; }
        
    }
    
}
